### ISSUE TITLE
任意のパスをビルドキャッシュの対象外とする

### ISSUE THREAD

**Issue by t2y** [HoshinoResort/hr-library-auto-update#2]
java (maven?) では `-SNAPSHOT` という接尾辞を使って開発中の jar のバージョンを表す。キャッシュを使うと SNAPSHOT の扱いでトラブルがあったため、SNAPSHOT を取り除いてビルドキャッシュを扱えないかを調査する。

**Comment by t2y** [comment]
github actions のドキュメントには exclude 設定についてなにも書いていない。

* https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows

**Comment by t2y** [comment]
一方で cache の github actions の readme には `!` を付けると exclude されるような記述がある。

```yaml
- name: Cache multiple paths
  uses: actions/cache@v2
  with:
    path: |
      ~/cache
      !~/cache/exclude
    key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
```

https://github.com/actions/cache
