### ISSUE TITLE
差分バージョンがあったことやリポジトリにコミットしたときの情報を取得したい

### ISSUE THREAD

**Issue by t2y** [HoshinoResort/hr-library-auto-update#6]
ライブラリのアップデートがあるときやリポジトリにコミットしたときにそのリビジョン番号がわかれば、通知などでその情報を含めることができる。スケジュール実行したときなどはあまり意識していないのでそういった情報があった方がよさそうに思える。

**Comment by t2y** [comment]
コミットしたときはそのリビジョン番号を返すようにする。

**Comment by t2y** [comment]
こんな感じで outputs を取得できる。

```yaml
      - name: Update library versions
        id: update
        uses: HoshinoResort/hr-library-auto-update@develop
        with:
          maven-test-command: "compile"
          display-dependency-updates: 'false'
          use-cache: 'true'
          custom-cache-path: '!~/.m2/repository/com'
          push-on-success: 'true'
          verbose: 'false'
      - run: |
          echo "has-updates: ${{ steps.update.outputs.has-updates }}"
          echo "revision: ${{ steps.update.outputs.revision }}"
```

```
has-updates: true
revision: a712589a48e6c35924ba9e456e4fd192ce4de48e
```
